K8SPS-283 update haproxy in docs
percona/k8sps-docs pull request #54
Opened 2023-09-01 10:18 UTC by fiowro

2023-09-03 21:10 UTC, fiowro commented on docs/haproxy-conf.md
> +* `cluster1-mysql-proxy` service selects MySQL cluster members to serve queries
Needs factchecking

2023-09-05 14:29 UTC, tplavcic requested changes

2023-09-05 14:29 UTC, tplavcic commented on docs/haproxy-conf.md
> +solution proxy when asynchronous replication betweem MySQL instances is turned,
```suggestion
solution proxy when asynchronous replication between MySQL instances is enabled,
```

2023-09-05 14:29 UTC, tplavcic commented on docs/haproxy-conf.md
> +     "router": {
```suggestion
     "proxy": {
```

2023-09-05 14:29 UTC, tplavcic commented on docs/haproxy-conf.md
> +until the upgraded Percona Distribution for MySQL luster member becomes synced,
```suggestion
until the upgraded Percona Distribution for MySQL cluster member becomes synced,
```

2023-09-05 14:29 UTC, tplavcic commented on docs/haproxy-conf.md
> +    enabled: true
I think usually we use two spaces indentation, but I might be wrong, please check.

2023-09-05 15:39 UTC, merged